# Generated by Django 5.1.5 on 2025-06-15 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('signal_id', models.IntegerField()),
                ('vehicle_count', models.IntegerField()),
                ('traffic_weight', models.FloatField()),
                ('green_time', models.IntegerField()),
                ('efficiency_score', models.FloatField()),
                ('Car', models.IntegerField(default=0)),
                ('Truck', models.IntegerField(default=0)),
                ('Motorcycle', models.IntegerField(default=0)),
                ('Bicycle', models.IntegerField(default=0)),
                ('Bus', models.IntegerField(default=0)),
            ],
        ),
    ]
