# Generated by Django 5.1.5 on 2025-06-16 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='processed_videos',
            field=models.FileField(blank=True, null=True, upload_to='processed_videos/'),
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
