# Generated by Django 5.1.5 on 2025-06-16 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_trafficlog_processed_videos_trafficlog_videos'),
    ]

    operations = [
        migrations.AddField(
            model_name='trafficlog',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
