# Generated by Django 5.1.5 on 2025-06-18 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_trafficlog_last_update'),
    ]

    operations = [
        migrations.CreateModel(
            name='JunctionSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='trafficlog',
            name='junction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.junctionsignals'),
        ),
    ]
